esphome:
  name: metatool1
  # Start the oscillation when the device boots


esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Metatool1 Fallback Hotspot"
    password: "DJjwCeDQqMD1"

captive_portal:

  # Example configuration entry
web_server:
  port: 80

output:
  - platform: ledc
    id: gpio14_output
    pin: GPIO14
    frequency: 1000 Hz

light:
  - platform: monochromatic
    name: "GPIO 14 LED Light"
    output: gpio14_output
    id: gpio_14_led_light

  - platform: neopixelbus
    id: "neopixel_light"
    type: GRB
    variant: WS2812
    pin: GPIO48
    num_leds: 60
    name: "NeoPixel Light"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO17
      mode:
        input: true
        pullup: true
    name: "Button 1"
    on_press:
      then:
        - light.turn_on: gpio_14_led_light
        - delay: 1s
        - light.turn_off: gpio_14_led_light
